title: SigneT Class Owners Association Noticeboard
email: secretary@sailsignet.org.uk
description: >- # this means to ignore newlines until "baseurl:"
  Noticeboard for the SigneT Class Owners Association
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
